source=~/.config/mango/env.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/mango_core.conf
source=~/.config/mango/mango_rules.conf
source=~/.config/mango/mango_bind.conf

# Autostart (polkit, clipboard, etc.)
exec-once=~/.config/mango/autostart.sh

# Clipboard history daemon
#exec-once=wl-paste --type text --watch cliphist store
exec-once=noctalia
#exec-once=caelestia-shell -d
